[PHP]
; Affichage des erreurs
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Configuration des logs
error_log = /Users/oconrard/Sites/Partageonslaforet/rando.partageonslaforet/logs/error.log
log_errors = On
log_errors_max_len = 1024

; Sessions
session.save_handler = files
session.save_path = "/Users/oconrard/Sites/Partageonslaforet/rando.partageonslaforet/sessions"
session.use_strict_mode = 1
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.cookie_secure = 1
session.cookie_httponly = 1
session.cookie_samesite = "Strict"
session.gc_maxlifetime = 1440

; Upload
upload_max_filesize = 10M
post_max_size = 10M

; Sécurité
expose_php = Off
max_execution_time = 30
max_input_time = 60
memory_limit = 128M

[Date]
date.timezone = "Europe/Paris"
